# Generated by Django 5.2.6 on 2026-05-08 17:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('entity_type', models.TextField(blank=True, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('diff_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vistoria',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('processo_n', models.CharField(blank=True, max_length=20, null=True)),
                ('requerente', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('nao_sincronizada', 'Nâo Sincronizada'), ('sincronizada', 'Sincronizada')], default='rascunho', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vistorias', to='vistorias.municipio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistorias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modulo', models.CharField(blank=True, max_length=10, null=True)),
                ('file_path_local', models.TextField(blank=True, null=True)),
                ('storage_path_remote', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(blank=True, max_length=50, null=True)),
                ('vistoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='vistorias.vistoria')),
            ],
        ),
        migrations.CreateModel(
            name='VistoriaAgricultura',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cultivo', models.TextField(blank=True, null=True)),
                ('cursos_hidricos_entorno', models.TextField(blank=True, null=True)),
                ('agrotoxicos', models.TextField(blank=True, null=True)),
                ('vistoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agricultura', to='vistorias.vistoria')),
            ],
        ),
        migrations.CreateModel(
            name='VistoriaAquicultura',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('qtd_tanques', models.IntegerField(blank=True, null=True)),
                ('hidrometro', models.BooleanField(blank=True, null=True)),
                ('outorga', models.BooleanField(blank=True, null=True)),
                ('fonte_agua', models.TextField(blank=True, null=True)),
                ('vistoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aquicultura', to='vistorias.vistoria')),
            ],
        ),
        migrations.CreateModel(
            name='VistoriaAvicultura',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modelo', models.CharField(blank=True, choices=[('CORTE', 'Corte'), ('POSTURA', 'Postura')], max_length=20, null=True)),
                ('tipo_criacao', models.TextField(blank=True, null=True)),
                ('qtd_animais', models.IntegerField(blank=True, null=True)),
                ('qtd_galpoes', models.IntegerField(blank=True, null=True)),
                ('qtd_modulos', models.IntegerField(blank=True, null=True)),
                ('qtd_gaiolas_modulo', models.IntegerField(blank=True, null=True)),
                ('aves_gaiola', models.IntegerField(blank=True, null=True)),
                ('gera_residuos', models.BooleanField(blank=True, null=True)),
                ('residuos_desc', models.TextField(blank=True, null=True)),
                ('vistoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avicultura', to='vistorias.vistoria')),
            ],
        ),
        migrations.CreateModel(
            name='VistoriaBovinocultura',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modelo', models.CharField(blank=True, choices=[('EXTENSIVO', 'Extensivo'), ('INTENSIVO', 'Intensivo')], max_length=20, null=True)),
                ('area_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dessedentacao', models.TextField(blank=True, null=True)),
                ('vistoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bovinocultura', to='vistorias.vistoria')),
            ],
        ),
        migrations.CreateModel(
            name='VistoriaSucroalcooleiro',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('residuos_solidos', models.TextField(blank=True, null=True)),
                ('bagaco', models.TextField(blank=True, null=True)),
                ('equipamentos_conformes', models.BooleanField(blank=True, null=True)),
                ('armazenamento_ok', models.BooleanField(blank=True, null=True)),
                ('vistoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sucroalcooleiro', to='vistorias.vistoria')),
            ],
        ),
        migrations.CreateModel(
            name='VistoriaSuinocultura',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('qtd_galpoes', models.IntegerField(blank=True, null=True)),
                ('qtd_animais', models.IntegerField(blank=True, null=True)),
                ('fase_producao', models.TextField(blank=True, null=True)),
                ('dejetos_destinacao', models.TextField(blank=True, null=True)),
                ('conformidade', models.BooleanField(blank=True, null=True)),
                ('vistoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suinocultura', to='vistorias.vistoria')),
            ],
        ),
        migrations.CreateModel(
            name='VistoriaSupressao',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tem_curso_dagua', models.BooleanField(blank=True, null=True)),
                ('app_preservada', models.BooleanField(blank=True, null=True)),
                ('indicios_uso_app', models.BooleanField(blank=True, null=True)),
                ('rl_isolada', models.BooleanField(blank=True, null=True)),
                ('rl_nativa_compativel', models.BooleanField(blank=True, null=True)),
                ('bioma', models.CharField(blank=True, choices=[('MA', 'Mata Atlântica'), ('CAATINGA', 'Caatinga')], max_length=20, null=True)),
                ('bloco_a_dap', models.BooleanField(blank=True, null=True)),
                ('bloco_a_altura', models.BooleanField(blank=True, null=True)),
                ('bloco_a_serapilheira', models.BooleanField(blank=True, null=True)),
                ('bloco_a_epifitas', models.BooleanField(blank=True, null=True)),
                ('bloco_a_subbosque', models.BooleanField(blank=True, null=True)),
                ('bloco_b_estrutura', models.TextField(blank=True, null=True)),
                ('presenca_invasoras', models.BooleanField(blank=True, null=True)),
                ('presenca_exoticas', models.BooleanField(blank=True, null=True)),
                ('especies', models.TextField(blank=True, null=True)),
                ('grau_infestacao', models.TextField(blank=True, null=True)),
                ('loc_app', models.TextField(blank=True, null=True)),
                ('loc_rl', models.TextField(blank=True, null=True)),
                ('loc_uas', models.TextField(blank=True, null=True)),
                ('pastos_abandonados', models.BooleanField(blank=True, null=True)),
                ('supressao_solo', models.BooleanField(blank=True, null=True)),
                ('fogo_app', models.BooleanField(blank=True, null=True)),
                ('fogo_rl', models.BooleanField(blank=True, null=True)),
                ('fogo_uas', models.BooleanField(blank=True, null=True)),
                ('fogo_outras', models.BooleanField(blank=True, null=True)),
                ('foto_geo_ok', models.BooleanField(blank=True, null=True)),
                ('infracao', models.TextField(blank=True, null=True)),
                ('medida_sugerida', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('vistoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supressao', to='vistorias.vistoria')),
            ],
        ),
    ]
