# Generated by Django 5.2.6 on 2026-05-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistoria',
            name='dispositivo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
