# Generated by Django 5.2.6 on 2026-05-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistoria',
            name='local_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
