# Generated by Django 5.2.6 on 2026-05-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistorias', '0002_vistoria_dispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistoriasupressao',
            name='bloco_a_altura_opcao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasupressao',
            name='bloco_a_dap_opcao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasupressao',
            name='bloco_a_epifitas_opcao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasupressao',
            name='bloco_a_estagio_sucessional',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasupressao',
            name='bloco_a_observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasupressao',
            name='bloco_a_serapilheira_opcao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasupressao',
            name='bloco_a_subbosque_opcao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
