# Generated by Django 5.2.6 on 2026-05-19 16:24

# pyrefly: ignore [missing-import]
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistorias', '0003_vistoriasupressao_bloco_a_altura_opcao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='corte_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='corte_aves_soltas_chao',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='corte_bebedouros_chao',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='corte_bebedouros_suspensos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='corte_cama_casca_arroz',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='corte_cama_destinacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='corte_cama_outros',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='corte_comedouros_chao',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='corte_comedouros_suspensos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='corte_comprimento',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='corte_densidade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='corte_frangos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='corte_galpoes_curtos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='corte_galpoes_longos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='corte_info_adicional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='corte_largura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='corte_pintos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='corte_qtd_estimada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='corte_sem_ventiladores',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='corte_sistema_criacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='corte_ventiladores',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='corte_ventiladores_func',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='foto_geo_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='infracao_constatada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='medida_sugerida',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='mortos_destinacao_alt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='mortos_incinerados',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='postura_andares',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='postura_aves_gaiola',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='postura_fileiras',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='postura_gaiolas_modulo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='postura_info_adicional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='postura_qtd_estimada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='postura_sistema_criacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='postura_tipo_confinamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaavicultura',
            name='residuos_detalhes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
