# Generated by Django 5.2.6 on 2026-05-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistorias', '0004_vistoriaavicultura_corte_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='acumulo_residuos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='dejetos_transbordando',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='destinacao_adequada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='fase_adulto',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='fase_adulto_qtd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='fase_matrizes',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='fase_matrizes_qtd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='fase_reprodutores',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='fase_reprodutores_qtd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='fase_terminacao',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='fase_terminacao_qtd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='foto_geo_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='impermeabilizacao_contencao',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='indicios_porte_maior',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='indicios_porte_maior_detalhe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='infracao_constatada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='medida_sugerida',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='modelo',
            field=models.CharField(blank=True, choices=[('CAIPIRA', 'Caipira'), ('INDUSTRIAL', 'Industrial')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='mortos_destino',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='mortos_incinerados',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='odor_extremo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='qtd_medio_por_galpao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasuinocultura',
            name='vazamento_dejetos',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
