# Generated by Django 5.2.6 on 2026-05-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistorias', '0005_vistoriasuinocultura_acumulo_residuos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistoriabovinocultura',
            name='foto_geo_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriabovinocultura',
            name='infracao_constatada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriabovinocultura',
            name='medida_sugerida',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriabovinocultura',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriabovinocultura',
            name='qtd_animais',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriabovinocultura',
            name='qtd_cochos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriabovinocultura',
            name='tamanho_cochos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
