# Generated by Django 5.2.6 on 2026-05-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistorias', '0006_vistoriabovinocultura_foto_geo_ok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistoriaaquicultura',
            name='area_tanques',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaaquicultura',
            name='bomba_identificada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaaquicultura',
            name='bomba_situacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaaquicultura',
            name='captacao_identificada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaaquicultura',
            name='captacao_situacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaaquicultura',
            name='descarte_residuos',
            field=models.CharField(blank=True, choices=[('COMPOSTEIRA', 'Composteira'), ('OUTRO', 'Outro')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaaquicultura',
            name='descarte_residuos_outro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaaquicultura',
            name='foto_geo_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaaquicultura',
            name='hidrometro_situacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaaquicultura',
            name='infracao_constatada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaaquicultura',
            name='medida_sugerida',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaaquicultura',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaaquicultura',
            name='outorga_identificacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaaquicultura',
            name='outros_itens_identificados',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaaquicultura',
            name='outros_itens_situacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaaquicultura',
            name='possui_aeradores',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaaquicultura',
            name='qtd_aeradores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaaquicultura',
            name='tubulacao_identificada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaaquicultura',
            name='tubulacao_situacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
