# Generated by Django 5.2.6 on 2026-05-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistorias', '0007_vistoriaaquicultura_area_tanques_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistoriaagricultura',
            name='agrotoxicos_embalagens_destinacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaagricultura',
            name='agrotoxicos_quais',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaagricultura',
            name='agrotoxicos_receituario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaagricultura',
            name='atividade_agricola',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaagricultura',
            name='atividade_irrigada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaagricultura',
            name='faz_uso_agrotoxicos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaagricultura',
            name='foto_geo_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaagricultura',
            name='infracao_constatada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaagricultura',
            name='infracao_sugestao_medidas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaagricultura',
            name='irrigada_outorga',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaagricultura',
            name='observacoes_complementares',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriaagricultura',
            name='tem_cursos_hidricos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='agrotoxicos_embalagens_destinacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='agrotoxicos_quais',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='agrotoxicos_receituario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='area_especifica_envase',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='armazenamento_requisitos_ambientais',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='bagaco_armazenamento_destinacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='chamines_controle_emissoes',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='efluentes_coleta_destinacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='efluentes_destinados_corretamente',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='envase_condicoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='equipamentos_memorial',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='faz_uso_agrotoxicos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='fontes_termicas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='fontes_termicas_quais',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='fossa_septica',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='foto_geo_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='gera_utiliza_bagaco',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='gestao_residuos_pgrs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='higienizacao_controle_efluentes',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='infracao_constatada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='infracao_sugestao_medidas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='lenha_local_armazenamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='lenha_nativa_exotica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='local_materia_prima',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='observacoes_complementares',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='produz_efluentes',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='produz_residuos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='residuos_coleta_destinacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='sistema_vinhaca',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='tanques_adequados',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='tanques_lagoas_impermeabilizadas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='utiliza_lenha',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='vazamentos_infiltracoes',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vistoriasucroalcooleiro',
            name='vinhaca_condicoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
