# Generated by Django 5.2.6 on 2026-05-22 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistorias', '0008_vistoriaagricultura_agrotoxicos_embalagens_destinacao_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VistoriaSucroalcooleiro',
            new_name='VistoriaAgroindustrial',
        ),
        migrations.AlterField(
            model_name='vistoriaagroindustrial',
            name='vistoria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agroindustrial', to='vistorias.vistoria'),
        ),
    ]
